# Change these first
owner: stryv-nl # Your GitHub organization or username, where this repository lives
repo: upptime-stryv.nl # The name of this repository

sites:
  - name: stryv.nl
    url: www.stryv.nl
    port: 443
    type: globalping
    check: tcp-ping
    location: Eindhoven
  - name: LiteSpeed Server
    url: www.stryv.nl/health-litespeed.php
    __dangerous__body_down_if_text_missing: 'OK'
    type: globalping
    location: Eindhoven
  - name: IMAP Server # Fastmail
    url: imap.fastmail.com
    port: 993
    type: globalping
    check: tcp-ping
    location: Eindhoven
  - name: SMTP Server # Fastmail
    url: smtp.fastmail.com
    port: 465
    type: globalping
    check: tcp-ping
    location: Eindhoven


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-stryv.nl
  logoUrl: https://www.stryv.nl/stryv-s.png
  name: Status STRYV
  introTitle: Uptime monitor and status page
  introMessage: 
  navbar:
    - title: Website
      href: https://www.stryv.nl
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


i18n:
  activeIncidents: Actieve incidenten
  allSystemsOperational: Alle systemen functioneren normaal
  incidentReport: "Incident #$NUMBER rapport →"
  activeIncidentSummary: Geopend op $DATE met $POSTS reacties
  incidentTitle: Incident $NUMBER details
  incidentDetails: Incidentdetails
  incidentFixed: Opgelost
  incidentOngoing: Lopend
  incidentOpenedAt: Geopend op
  incidentClosedAt: Gesloten op
  incidentViewOnGitHub: Bekijk en abonneer op GitHub
  incidentCommentSummary: Geplaatst op $DATE door $AUTHOR
  incidentBack: ← Terug naar alle incidenten
  pastIncidents: Vorige incidenten
  pastIncidentsResolved: Opgelost in $MINUTES minuten met $POSTS reacties
  liveStatus: Live status
  overallUptime: "Totale uptime: $UPTIME"
  overallUptimeTitle: Totale uptime
  averageResponseTime: "Gemiddelde responstijd: $TIMEms"
  averageResponseTimeTitle: Gemiddelde responstijd
  sevelDayResponseTime: Responstijd over 7 dagen
  responseTimeMs: Responstijd (ms)
  up: Online
  down: Offline
  degraded: Gedegradeerde prestaties  
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer: Deze pagina is [open source]($REPO) en wordt aangedreven door [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Verzoeklimiet overschreden
  rateLimitExceededIntro: Je hebt het maximale aantal toegestane verzoeken per uur overschreden. Wacht even voordat je deze website opnieuw probeert te laden. Je kunt ook een GitHub Personal Access Token toevoegen om verder te gaan.
  rateLimitExceededWhatDoesErrorMean: Wat betekent deze foutmelding?  
  rateLimitExceededErrorMeaning: Deze website gebruikt de GitHub-API om realtime gegevens over onze websites te tonen. GitHub staat standaard 60 verzoeken per uur toe per IP-adres, en die limiet heb je bereikt.
  rateLimitExceededErrorHowCanFix: Hoe los ik dit op?
  rateLimitExceededErrorFix: Wacht een uur zodat de limiet wordt gereset, of voeg je eigen GitHub Personal Access Token toe om 5.000 verzoeken per uur te krijgen.
  rateLimitExceededGeneratePAT: Lees hoe je een Personal Access Token aanmaakt
  rateLimitExceededHasSet: Je hebt al een Personal Access Token ingesteld.
  rateLimitExceededRemoveToken: Token verwijderen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Kopieer en plak je token
  rateLimitExceededSaveToken: Token opslaan
  errorTitle: Er is een fout opgetreden
  errorIntro: Er is een fout opgetreden bij het ophalen van de meest recente statusinformatie.
  errorText: Probeer het over een paar minuten opnieuw.
  errorHome: Ga naar de startpagina
  pastScheduledMaintenance: Afgeronde onderhoudsperiodes
  scheduledMaintenance: Gepland onderhoud
  scheduledMaintenanceSummaryStarted: Gestart op $DATE voor $DURATION minuten
  scheduledMaintenanceSummaryStarts: Start op $DATE en duurt $DURATION minuten
  startedAt: Gestart op
  startsAt: Start op
  duration: Duur
  durationMin: $DURATION minuten
  incidentCompleted: Voltooid
  incidentScheduled: Gepland
  duration24H: 24u
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1j
  durationAll: alles
  locale: nl-NL
  url: "URL"
  status: "Status"
  history: "Geschiedenis"
  responseTime: "Responstijd"
  uptime: "Uptime"
  up: "🟩 Online"
  degraded: "🟨 Verminderde prestaties"
  down: "🟥 Offline"
  responseTimeGraphAlt: "Responstijdgrafiek"
  ms: "ms"
  responseTime: "Responstijd"
  responseTimeDay: "Responstijd (24 uur)"
  responseTimeWeek: "Responstijd (7 dagen)"
  responseTimeMonth: "Responstijd (30 dagen)"
  responseTimeYear: "Responstijd (1 jaar)"
  uptime: "Totale uptime"
  uptimeDay: "Uptime (24 uur)"
  uptimeWeek: "Uptime (7 dagen)"
  uptimeMonth: "Uptime (30 dagen)"
  uptimeYear: "Uptime (1 jaar)"
  liveStatus: "Live status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 Alle systemen operationeel"
  degradedPerformance: "🟨 Verminderde prestaties"
  completeOutage: "🟥 Volledige storing"
  partialOutage: "🟧 Gedeeltelijke storing"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
