# Change these first
owner: stryv-nl # Your GitHub organization or username, where this repository lives
repo: upptime-stryv.nl # The name of this repository

sites:
  - name: Website
    url: www.stryv.nl
    type: globalping
    check: tcp-ping
    location: Eindhoven
  - name: Web Server
    url: www.stryv.nl:2083
    type: globalping
    check: tcp-ping
    location: Eindhoven
  - name: IMAP Server # Fastmail
    url: imap.fastmail.com
    port: 993
    type: globalping
    check: tcp-ping
    location: Eindhoven
  - name: SMTP Server # Fastmail
    url: smtp.fastmail.com
    port: 465
    type: globalping
    check: tcp-ping
    location: Eindhoven


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-stryv.nl
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime STRYV
  introTitle: Uptime monitor and status page
  introMessage: 
  navbar:
    - title: Website
      href: https://www.stryv.nl
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
